
server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mohist-examples?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password:

logging:
  level:
    root: info
    mohist.examples.spring.springboot: debug
