
package com.kuhnwei.mohist.examples.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExampleFacotry", targetNamespace = "http://mohist.kuhnwei.com/examples/webservice/client/", wsdlLocation = "http://127.0.0.1:8080/webservice/example?wsdl")
public class ExampleFacotry
    extends Service
{

    private final static URL EXAMPLEFACOTRY_WSDL_LOCATION;
    private final static WebServiceException EXAMPLEFACOTRY_EXCEPTION;
    private final static QName EXAMPLEFACOTRY_QNAME = new QName("http://mohist.kuhnwei.com/examples/webservice/client/", "ExampleFacotry");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/webservice/example?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMPLEFACOTRY_WSDL_LOCATION = url;
        EXAMPLEFACOTRY_EXCEPTION = e;
    }

    public ExampleFacotry() {
        super(__getWsdlLocation(), EXAMPLEFACOTRY_QNAME);
    }

    public ExampleFacotry(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMPLEFACOTRY_QNAME, features);
    }

    public ExampleFacotry(URL wsdlLocation) {
        super(wsdlLocation, EXAMPLEFACOTRY_QNAME);
    }

    public ExampleFacotry(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMPLEFACOTRY_QNAME, features);
    }

    public ExampleFacotry(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExampleFacotry(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExampleService
     */
    @WebEndpoint(name = "ExampleServiceInstance")
    public ExampleService getExampleServiceInstance() {
        return super.getPort(new QName("http://mohist.kuhnwei.com/examples/webservice/client/", "ExampleServiceInstance"), ExampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExampleService
     */
    @WebEndpoint(name = "ExampleServiceInstance")
    public ExampleService getExampleServiceInstance(WebServiceFeature... features) {
        return super.getPort(new QName("http://mohist.kuhnwei.com/examples/webservice/client/", "ExampleServiceInstance"), ExampleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMPLEFACOTRY_EXCEPTION!= null) {
            throw EXAMPLEFACOTRY_EXCEPTION;
        }
        return EXAMPLEFACOTRY_WSDL_LOCATION;
    }

}
