
package com.kuhnwei.mohist.examples.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExampleService", targetNamespace = "http://mohist.kuhnwei.com/examples/webservice/client/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExampleService {


    /**
     * 
     * @param message
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "print", targetNamespace = "http://mohist.kuhnwei.com/examples/webservice/client/", className = "com.kuhnwei.mohist.examples.webservice.client.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://mohist.kuhnwei.com/examples/webservice/client/", className = "com.kuhnwei.mohist.examples.webservice.client.PrintResponse")
    @Action(input = "http://mohist.kuhnwei.com/examples/webservice/client/ExampleService/printRequest", output = "http://mohist.kuhnwei.com/examples/webservice/client/ExampleService/printResponse")
    public String print(
            @WebParam(name = "message", targetNamespace = "")
                    String message);

}
