server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mohist-examples?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password:

mybatis:
  configuration:
    cache-enabled: true                 # 设置映射器中的缓存开关; default: true
    # lazy-loading-enabled: false         # 延迟加载开关; default: false
    # aggressive-lazy-loading: true       # 当启用时,对任意延迟属性的调用会使带有延迟加载属性的对象完整加载; 反之,每种属性将会按需加载. default：true
    # multiple-result-sets-enabled: true  # 是否允许单一语句返回多结果集（需要兼容驱动）; default：true
    # use-column-label: true              # 使用列标签代替列名, 不同的驱动在这方面会有不同的表现。default：true
    # use-generated-keys: false           # 允许 JDBC 支持自动生成主键，需要驱动兼容。如果设置为 true 则这个设置强制使用自动生成主键，尽管一些驱动不能兼容但仍可正常工作。default：false
    # auto-mapping-behavior: partial      # 指定 MyBatis 应如何自动映射列到字段或属性。NONE 表示取消自动映射；PARTIAL 只会自动映射没有定义嵌套结果集映射的结果集；FULL 会自动映射任意复杂的结果集（无论是否嵌套）。default：partial
    # default-executor-type: simple       # 配置默认的执行器。SIMPLE 就是普通的执行器；REUSE 执行器会重用预处理语句（prepared statements）；BATCH 执行器将重用语句并执行批量更新。
    # default-statement-timeout: 30000    # 设置超时时间，它决定驱动等待数据库响应的秒数。
    # default-fetch-size: null;         # Sets the driver a hint as to control fetching size for return results. This parameter value can be override by a query setting.
    # safe-row-bounds-enabled: false      # 允许在嵌套语句中使用分页（RowBounds）。default：false. default：false
    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射default：false
    # local-cache-scope: session          # MyBatis 利用本地缓存机制（Local Cache）防止循环引用（circular references）和加速重复嵌套查询。默认值为 SESSION，这种情况下会缓存一个会话中执行的所有查询。若设置值为 STATEMENT，本地会话仅用在语句执行上，对相同 SqlSession 的不同调用将不会共享数据。default：SESSION
    # jdbc-type-for-null: other           # 当没有为参数提供特定的 JDBC 类型时，为空值指定 JDBC 类型。某些驱动需要指定列的 JDBC 类型，多数情况直接用一般类型即可，比如 NULL、VARCHAR 或 OTHER。default：OTHER
    # lazy-load-trigger-methods: equals,clone,hashCode,toString # 指定哪个对象的方法触发一次延迟加载。
    # default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver # 指定动态 SQL 生成的默认语言。default：false
    # call-setters-on-nulls: false        # default：false
    # log-prefix:                         # 指定 MyBatis 增加到日志名称的前缀。
    # log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 指定 MyBatis 所用日志的具体实现，未指定时将自动查找。
    # proxy-factory: JAVASSIST            # 指定 Mybatis 创建具有延迟加载能力的对象所用到的代理工具。
  type-aliases-package: mohist.examples.spring.springboot.entity


logging:
  level:
    root: info
    mohist.examples.spring.springboot: debug
