
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-boot
    username: root
    password:

logging:
  pattern:
    console: "%d{ISO8601} %-5p [%F:%L] : %m%n"
  level:
    root: info
    com.szatc.demo: debug
