
server:
  port: 80

spring:
  task:
    scheduling:
      pool:
        size: 5

logging:
  level:
    root: info
    mohist.examples.spring.springboot: debug
  file: logs/springboot-mqtt.log

mohist:
  mqtt:
    server-uris: "tcp://192.168.1.224:1883"
    username: admin
    password: admin
